begin;
create extension if not exists pgtap with schema extensions;
set search_path=public,extensions;
select plan(29);
create temporary table activity_baseline as select * from public.activities;
create temporary table activity_fixtures(slot integer,id integer);
grant select on activity_baseline to authenticated;
grant select,insert on activity_fixtures to authenticated;
insert into auth.users(id) values('00000000-0000-0000-0000-000000000401'),('00000000-0000-0000-0000-000000000402');
insert into private.publications_admins(user_id) values('00000000-0000-0000-0000-000000000401');
set local role anon;
select throws_ok($$select public.admin_save_activity()$$,'42501',null,'Anonymous cannot add');
select throws_ok($$select public.admin_delete_activity(1,now(),true)$$,'42501',null,'Anonymous cannot delete');
select throws_ok($$select public.admin_move_activity(1,'2026',1,array[1])$$,'42501',null,'Anonymous cannot reorder');
reset role;
select set_config('request.jwt.claims','{"sub":"00000000-0000-0000-0000-000000000402","role":"authenticated","user_metadata":{"admin":true}}',true);
set local role authenticated;
select throws_ok($$select public.admin_save_activity()$$,'42501',null,'Non-admin cannot add');
select throws_ok($$select public.admin_save_activity(1,'{}',now())$$,'42501',null,'Non-admin cannot edit');
select throws_ok($$select public.admin_delete_activity(1,now(),true)$$,'42501',null,'Non-admin cannot delete');
select throws_ok($$select public.admin_move_activity(1,'2026',1,array[1])$$,'42501',null,'Non-admin cannot reorder');
reset role;
select set_config('request.jwt.claims','{"sub":"00000000-0000-0000-0000-000000000401","role":"authenticated"}',true);
set local role authenticated;
select lives_ok($$insert into activity_fixtures select 1,public.admin_save_activity(p_activity=>' {"year":"9996","title":"TEMP ACTIVITY A","activity_type":"FDP","institution":"Test institution","date_text":"  "}')$$,'Admin adds with empty optional metadata');
select lives_ok($$insert into activity_fixtures select 2,public.admin_save_activity(p_activity=>' {"year":"9996","title":"TEMP ACTIVITY B","activity_type":"Workshop","institution":"Test institution"}')$$,'Admin adds second activity');
select lives_ok($$insert into activity_fixtures select 3,public.admin_save_activity(p_activity=>' {"year":"9997","title":"TEMP ACTIVITY C","activity_type":"Conference","institution":"Test institution"}')$$,'Admin adds destination-year activity');
select ok((select date_text is null and duration_text is null and details is null and proof_url is null and source_order is null from public.activities where id=(select id from activity_fixtures where slot=1)),'Empty optionals and new source order are NULL');
select is((select display_order from public.activities where id=(select id from activity_fixtures where slot=2)),2,'New record appends within selected year');
select lives_ok($$select public.admin_save_activity(id,'{"year":"9996","title":"TEMP ACTIVITY A edited","activity_type":"FDP","institution":" Exact wording ","date_text":"21 & 24 December","duration_text":"Two-week Value-Added Course","details":" Supplied details ","proof_url":"https://example.com/proof?usp=drive_link"}',updated_at) from public.activities where id=(select id from activity_fixtures where slot=1)$$,'Admin can edit');
select ok((select institution=' Exact wording ' and date_text='21 & 24 December' and duration_text='Two-week Value-Added Course' and details=' Supplied details ' and proof_url='https://example.com/proof?usp=drive_link' from public.activities where id=(select id from activity_fixtures where slot=1)),'Supplied metadata and proof URL preserved exactly');
select throws_ok($$select public.admin_save_activity((select id from activity_fixtures where slot=1),'{}','2000-01-01')$$,'P0001',null,'Stale edit rejected');
select lives_ok($$select public.admin_move_activity((select id from activity_fixtures where slot=2),'9996',1,(select array_agg(id order by display_order) from public.activities where year='9996'))$$,'Admin reorders within year');
select is((select display_order from public.activities where id=(select id from activity_fixtures where slot=2)),1,'Reordered record takes requested position');
select throws_ok($$select public.admin_move_activity((select id from activity_fixtures where slot=3),'9996',1,(select array_agg(id order by display_order) from public.activities where year='9996'))$$,'22023',null,'Reorder cannot cross years');
select throws_ok($$select public.admin_move_activity((select id from activity_fixtures where slot=2),'9996',1,array[1])$$,'P0001',null,'Stale year order rejected');
select lives_ok($$select public.admin_save_activity(id,'{"year":"9997","title":"TEMP ACTIVITY A moved","activity_type":"FDP","institution":"Test institution"}',updated_at) from public.activities where id=(select id from activity_fixtures where slot=1)$$,'Admin changes activity year');
select is((select display_order from public.activities where id=(select id from activity_fixtures where slot=1)),2,'Year change appends at destination');
select ok((select count(*)=count(distinct (year,display_order)) and min(display_order)>0 from public.activities),'Year positions remain valid and unique');
select is((select count(*)::integer from public.activities where year='9997'),2,'Destination year count updates');
select throws_ok($$select public.admin_save_activity(p_activity=>' {"year":"9997","title":"Bad category","activity_type":"Unknown","institution":"Test"}')$$,'23503',null,'Unlisted category rejected');
select throws_ok($$select public.admin_delete_activity(id,updated_at,false) from public.activities where id=(select id from activity_fixtures where slot=1)$$,'22023',null,'Delete requires confirmation');
select lives_ok($$select public.admin_delete_activity(a.id,a.updated_at,true) from public.activities a join activity_fixtures f using(id)$$,'Admin deletes confirmed test records');
select is((select count(*)::integer from public.activities),(select count(*)::integer from activity_baseline),'Original count restored');
select ok(not exists(select 1 from activity_baseline b full join public.activities a using(id) where to_jsonb(b) is distinct from to_jsonb(a)),'Every original row including metadata order and timestamps unchanged');
reset role;
delete from private.publications_admins where user_id='00000000-0000-0000-0000-000000000401';
set local role authenticated;
select throws_ok($$select public.admin_save_activity()$$,'42501',null,'Revoked admin cannot write');
select * from finish();
rollback;
