-- Peer Reviews foundation and independent public counters.
begin;

create table public.peer_reviews (
  id integer generated by default as identity primary key,
  review_text text not null check (length(btrim(review_text)) > 0),
  source_order integer check (source_order > 0),
  display_order integer not null check (display_order > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint peer_reviews_display_order_unique
    unique (display_order) deferrable initially immediate
);

create trigger peer_reviews_timestamps
before insert or update on public.peer_reviews
for each row execute function private.set_record_timestamps();

alter table public.peer_reviews enable row level security;
revoke all on table public.peer_reviews from public, anon, authenticated;
grant select on table public.peer_reviews to anon, authenticated;
grant insert, update, delete on table public.peer_reviews to authenticated;
revoke all on sequence public.peer_reviews_id_seq from public, anon, authenticated;
grant usage on sequence public.peer_reviews_id_seq to authenticated;

create policy peer_reviews_public_read on public.peer_reviews
for select to anon, authenticated using (true);

create policy peer_reviews_admin_insert on public.peer_reviews
for insert to authenticated
with check ((select public.is_publications_admin()));

create policy peer_reviews_admin_update on public.peer_reviews
for update to authenticated
using ((select public.is_publications_admin()))
with check ((select public.is_publications_admin()));

create policy peer_reviews_admin_delete on public.peer_reviews
for delete to authenticated
using ((select public.is_publications_admin()));

create table public.peer_review_settings (
  singleton boolean primary key default true check (singleton),
  hero_counter_text text not null check (length(btrim(hero_counter_text)) > 0),
  completed_reviews_count integer not null check (completed_reviews_count >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger peer_review_settings_timestamps
before insert or update on public.peer_review_settings
for each row execute function private.set_record_timestamps();

alter table public.peer_review_settings enable row level security;
revoke all on table public.peer_review_settings from public, anon, authenticated;
grant select on table public.peer_review_settings to anon, authenticated;
grant update on table public.peer_review_settings to authenticated;

create policy peer_review_settings_public_read on public.peer_review_settings
for select to anon, authenticated using (true);

create policy peer_review_settings_admin_update on public.peer_review_settings
for update to authenticated
using ((select public.is_publications_admin()))
with check ((select public.is_publications_admin()));

commit;
