begin;

-- No publication records, settings values, or admin identities are seeded here.
create schema if not exists private;
revoke all on schema private from public, anon, authenticated;

create table private.publications_admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);
alter table private.publications_admins enable row level security;
revoke all on table private.publications_admins from public, anon, authenticated;

-- No user-supplied identifier or editable metadata controls authorization.
create function public.is_publications_admin()
returns boolean
language sql stable security definer
set search_path = ''
as $$
  select exists (
    select 1 from private.publications_admins
    where user_id = (select auth.uid())
  );
$$;
revoke all on function public.is_publications_admin() from public, anon, authenticated;
grant execute on function public.is_publications_admin() to authenticated;

create table public.publications (
  id integer generated by default as identity primary key,
  title text not null check (length(btrim(title)) > 0),
  year text not null check (year ~ '^[0-9]{4}$'),
  journal text not null check (length(btrim(journal)) > 0),
  indexing text[] not null default '{}',
  doi text,
  article_url text,
  proof_url text,
  publication_type text check (publication_type in ('Journal Article', 'Book Chapter', 'Conference Proceeding')),
  impact_factor numeric check (impact_factor >= 0 and impact_factor <> 'NaN'::numeric),
  source_order integer check (source_order > 0),
  display_order integer not null check (display_order > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  -- Deferrable so a future admin transaction can swap positions atomically.
  constraint publications_display_order_unique unique (display_order) deferrable initially immediate
);

create table public.publication_settings (
  id boolean primary key default true check (id = true),
  hero_publications text not null check (length(btrim(hero_publications)) > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create function private.set_record_timestamps()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if tg_op = 'INSERT' then
    new.created_at := now();
  else
    new.created_at := old.created_at;
  end if;
  new.updated_at := now();
  return new;
end;
$$;
revoke all on function private.set_record_timestamps() from public, anon, authenticated;

create trigger publications_timestamps before insert or update on public.publications
for each row execute function private.set_record_timestamps();
create trigger publication_settings_timestamps before insert or update on public.publication_settings
for each row execute function private.set_record_timestamps();

alter table public.publications enable row level security;
alter table public.publication_settings enable row level security;

revoke all on table public.publications, public.publication_settings from public, anon, authenticated;
grant select on table public.publications, public.publication_settings to anon, authenticated;
grant insert, update, delete on table public.publications, public.publication_settings to authenticated;
revoke all on sequence public.publications_id_seq from public, anon, authenticated;
grant usage on sequence public.publications_id_seq to authenticated;

create policy publications_public_read on public.publications
for select to anon, authenticated using (true);
create policy publications_admin_insert on public.publications
for insert to authenticated with check ((select public.is_publications_admin()));
create policy publications_admin_update on public.publications
for update to authenticated using ((select public.is_publications_admin()))
with check ((select public.is_publications_admin()));
create policy publications_admin_delete on public.publications
for delete to authenticated using ((select public.is_publications_admin()));

create policy publication_settings_public_read on public.publication_settings
for select to anon, authenticated using (true);
create policy publication_settings_admin_insert on public.publication_settings
for insert to authenticated with check ((select public.is_publications_admin()));
create policy publication_settings_admin_update on public.publication_settings
for update to authenticated using ((select public.is_publications_admin()))
with check ((select public.is_publications_admin()));
create policy publication_settings_admin_delete on public.publication_settings
for delete to authenticated using ((select public.is_publications_admin()));

commit;
