begin;

create or replace function public.project_name_array_valid(p_names text[])
returns boolean language sql immutable set search_path = '' as $$
  select p_names is null or (
    cardinality(p_names) > 0
    and array_position(p_names, null) is null
    and not exists (select 1 from unnest(p_names) as items(value) where btrim(value) = '')
  );
$$;
revoke all on function public.project_name_array_valid(text[]) from public;
grant execute on function public.project_name_array_valid(text[]) to anon, authenticated;

create table if not exists public.projects_guided (
  id integer generated by default as identity primary key,
  project_title text not null check (length(btrim(project_title)) > 0),
  project_level text,
  degree_program text,
  branch text,
  academic_year text,
  batch text,
  student_names text[] check (public.project_name_array_valid(student_names)),
  guide_name text,
  co_guide_names text[] check (public.project_name_array_valid(co_guide_names)),
  proof_url text check (
    proof_url is null or (
      proof_url ~* '^https?://[^[:space:]]+$'
      and proof_url !~* '^https?://[^/]*@'
    )
  ),
  source_order integer check (source_order > 0),
  display_order integer not null check (display_order > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint projects_guided_display_order_unique
    unique (display_order) deferrable initially immediate
);

drop trigger if exists projects_guided_timestamps on public.projects_guided;
create trigger projects_guided_timestamps
before insert or update on public.projects_guided
for each row execute function private.set_record_timestamps();

alter table public.projects_guided enable row level security;
revoke all on table public.projects_guided from public, anon, authenticated;
grant select on table public.projects_guided to anon, authenticated;
grant insert, update, delete on table public.projects_guided to authenticated;
revoke all on sequence public.projects_guided_id_seq from public, anon, authenticated;
grant usage on sequence public.projects_guided_id_seq to authenticated;

drop policy if exists projects_guided_public_read on public.projects_guided;
create policy projects_guided_public_read on public.projects_guided
for select to anon, authenticated using (true);
drop policy if exists projects_guided_admin_insert on public.projects_guided;
create policy projects_guided_admin_insert on public.projects_guided
for insert to authenticated with check ((select public.is_publications_admin()));
drop policy if exists projects_guided_admin_update on public.projects_guided;
create policy projects_guided_admin_update on public.projects_guided
for update to authenticated using ((select public.is_publications_admin()))
with check ((select public.is_publications_admin()));
drop policy if exists projects_guided_admin_delete on public.projects_guided;
create policy projects_guided_admin_delete on public.projects_guided
for delete to authenticated using ((select public.is_publications_admin()));

commit;
