begin;

create table if not exists public.subjects_taught (
  id integer generated by default as identity primary key,
  subject_name text not null check (length(btrim(subject_name)) > 0),
  course_code text,
  program text,
  branch text,
  semester text,
  academic_year text,
  subject_type text,
  proof_url text,
  source_order integer check (source_order > 0),
  display_order integer not null check (display_order > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint subjects_taught_display_order_unique
    unique (display_order) deferrable initially immediate
);

drop trigger if exists subjects_taught_timestamps on public.subjects_taught;
create trigger subjects_taught_timestamps
before insert or update on public.subjects_taught
for each row execute function private.set_record_timestamps();

alter table public.subjects_taught enable row level security;
revoke all on table public.subjects_taught from public, anon, authenticated;
grant select on table public.subjects_taught to anon, authenticated;
grant insert, update, delete on table public.subjects_taught to authenticated;
revoke all on sequence public.subjects_taught_id_seq from public, anon, authenticated;
grant usage on sequence public.subjects_taught_id_seq to authenticated;

drop policy if exists subjects_taught_public_read on public.subjects_taught;
create policy subjects_taught_public_read on public.subjects_taught
for select to anon, authenticated using (true);
drop policy if exists subjects_taught_admin_insert on public.subjects_taught;
create policy subjects_taught_admin_insert on public.subjects_taught
for insert to authenticated with check ((select public.is_publications_admin()));
drop policy if exists subjects_taught_admin_update on public.subjects_taught;
create policy subjects_taught_admin_update on public.subjects_taught
for update to authenticated using ((select public.is_publications_admin()))
with check ((select public.is_publications_admin()));
drop policy if exists subjects_taught_admin_delete on public.subjects_taught;
create policy subjects_taught_admin_delete on public.subjects_taught
for delete to authenticated using ((select public.is_publications_admin()));

commit;
