begin;

create table if not exists public.professional_memberships (
  id integer generated by default as identity primary key,
  organization_name text not null check (length(btrim(organization_name)) > 0),
  membership_type text,
  membership_number text,
  date_text text,
  validity_text text,
  designation text,
  chapter text,
  proof_url text,
  source_order integer check (source_order > 0),
  display_order integer not null check (display_order > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint professional_memberships_display_order_unique
    unique (display_order) deferrable initially immediate
);

drop trigger if exists professional_memberships_timestamps on public.professional_memberships;
create trigger professional_memberships_timestamps
before insert or update on public.professional_memberships
for each row execute function private.set_record_timestamps();

alter table public.professional_memberships enable row level security;
revoke all on table public.professional_memberships from public, anon, authenticated;
grant select on table public.professional_memberships to anon, authenticated;
grant insert, update, delete on table public.professional_memberships to authenticated;
revoke all on sequence public.professional_memberships_id_seq from public, anon, authenticated;
grant usage on sequence public.professional_memberships_id_seq to authenticated;

drop policy if exists professional_memberships_public_read on public.professional_memberships;
create policy professional_memberships_public_read on public.professional_memberships
for select to anon, authenticated using (true);
drop policy if exists professional_memberships_admin_insert on public.professional_memberships;
create policy professional_memberships_admin_insert on public.professional_memberships
for insert to authenticated with check ((select public.is_publications_admin()));
drop policy if exists professional_memberships_admin_update on public.professional_memberships;
create policy professional_memberships_admin_update on public.professional_memberships
for update to authenticated using ((select public.is_publications_admin()))
with check ((select public.is_publications_admin()));
drop policy if exists professional_memberships_admin_delete on public.professional_memberships;
create policy professional_memberships_admin_delete on public.professional_memberships
for delete to authenticated using ((select public.is_publications_admin()));

commit;
