begin;

create table public.certifications (
  id integer generated by default as identity primary key,
  title text not null check (length(btrim(title)) > 0),
  certificate_url text,
  fdp_url text,
  source_order integer check (source_order > 0),
  display_order integer not null check (display_order > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  -- Deferrable ordering allows an admin transaction to swap card positions.
  constraint certifications_display_order_unique
    unique (display_order) deferrable initially immediate
);

create trigger certifications_timestamps
before insert or update on public.certifications
for each row execute function private.set_record_timestamps();

alter table public.certifications enable row level security;

revoke all on table public.certifications from public, anon, authenticated;
grant select on table public.certifications to anon, authenticated;
grant insert, update, delete on table public.certifications to authenticated;
revoke all on sequence public.certifications_id_seq from public, anon, authenticated;
grant usage on sequence public.certifications_id_seq to authenticated;

create policy certifications_public_read on public.certifications
for select to anon, authenticated using (true);

create policy certifications_admin_insert on public.certifications
for insert to authenticated
with check ((select public.is_publications_admin()));

create policy certifications_admin_update on public.certifications
for update to authenticated
using ((select public.is_publications_admin()))
with check ((select public.is_publications_admin()));

create policy certifications_admin_delete on public.certifications
for delete to authenticated
using ((select public.is_publications_admin()));

commit;
