-- Achievements / Awards foundation only. No achievement records are seeded.
begin;

create table public.achievements (
  id integer generated by default as identity primary key,
  title text not null check (length(btrim(title)) > 0),
  description text not null,
  proof_url text,
  extra_proof_url text,
  source_order integer check (source_order > 0),
  display_order integer not null check (display_order > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint achievements_display_order_unique
    unique (display_order) deferrable initially immediate
);

create trigger achievements_timestamps
before insert or update on public.achievements
for each row execute function private.set_record_timestamps();

alter table public.achievements enable row level security;

revoke all on table public.achievements from public, anon, authenticated;
grant select on table public.achievements to anon, authenticated;
grant insert, update, delete on table public.achievements to authenticated;
revoke all on sequence public.achievements_id_seq from public, anon, authenticated;
grant usage on sequence public.achievements_id_seq to authenticated;

create policy achievements_public_read on public.achievements
for select to anon, authenticated using (true);

create policy achievements_admin_insert on public.achievements
for insert to authenticated
with check ((select public.is_publications_admin()));

create policy achievements_admin_update on public.achievements
for update to authenticated
using ((select public.is_publications_admin()))
with check ((select public.is_publications_admin()));

create policy achievements_admin_delete on public.achievements
for delete to authenticated
using ((select public.is_publications_admin()));

commit;
