-- Activities foundation only: no activity records or public read-path changes.
begin;

create table public.activity_categories (
  label text primary key check (length(btrim(label)) > 0),
  display_order integer not null check (display_order > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint activity_categories_order_unique unique (display_order) deferrable initially immediate
);

insert into public.activity_categories (label, display_order) values
('Conference',1),('FDP',2),('Organizing',3),('Guest Lecture',4),
('Training',5),('Workshop',6),('STTP',7),('Webinar',8),('Quiz',9),
('Resource Person',10),('Seminar',11);

create table public.activities (
  id integer generated by default as identity primary key,
  year text not null check (year ~ '^[0-9]{4}$'),
  title text not null check (length(btrim(title)) > 0),
  activity_type text not null references public.activity_categories(label)
    on update restrict on delete restrict,
  institution text not null check (length(btrim(institution)) > 0),
  date_text text,
  duration_text text,
  details text,
  proof_url text,
  source_order integer check (source_order > 0),
  display_order integer not null check (display_order > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint activities_year_order_unique unique (year, display_order) deferrable initially immediate
);

create index activities_public_order on public.activities (year desc, display_order asc);
create index activities_category on public.activities (activity_type);
create trigger activities_timestamps before insert or update on public.activities
for each row execute function private.set_record_timestamps();
create trigger activity_categories_timestamps before insert or update on public.activity_categories
for each row execute function private.set_record_timestamps();

alter table public.activities enable row level security;
alter table public.activity_categories enable row level security;
revoke all on table public.activities, public.activity_categories from public, anon, authenticated;
grant select on table public.activities, public.activity_categories to anon, authenticated;
grant insert, update, delete on table public.activities, public.activity_categories to authenticated;
revoke all on sequence public.activities_id_seq from public, anon, authenticated;
grant usage on sequence public.activities_id_seq to authenticated;

-- Reuse the existing trusted UUID allowlist; editable user metadata never authorizes writes.
create policy activities_public_read on public.activities
for select to anon, authenticated using (true);
create policy activities_admin_insert on public.activities
for insert to authenticated with check ((select public.is_publications_admin()));
create policy activities_admin_update on public.activities
for update to authenticated using ((select public.is_publications_admin()))
with check ((select public.is_publications_admin()));
create policy activities_admin_delete on public.activities
for delete to authenticated using ((select public.is_publications_admin()));

create policy activity_categories_public_read on public.activity_categories
for select to anon, authenticated using (true);
create policy activity_categories_admin_insert on public.activity_categories
for insert to authenticated with check ((select public.is_publications_admin()));
create policy activity_categories_admin_update on public.activity_categories
for update to authenticated using ((select public.is_publications_admin()))
with check ((select public.is_publications_admin()));
create policy activity_categories_admin_delete on public.activity_categories
for delete to authenticated using ((select public.is_publications_admin()));

commit;
